### ISSUE TITLE
Spelling error: “Reource”

### ISSUE THREAD

**Issue by sftim** [aws/aws-auto-scaling-custom-resource#16]
`PreProdReourceIdPrefix` contains a spelling mistake in (eg) https://github.com/aws/aws-auto-scaling-custom-resource/blob/9783b5768550092471c6530091c8425b58a0e040/cloudformation/templates/custom-resource-mock-stack.yaml#L532.

**Comment by Nayanish** [comment]
Fix merged to master. Thanks for the contribution.
